Repository Tong-Hana/tonghana, pull requests merged in 2025-06, with the labels that each got.

#9 [feat] 회원가입/로그인 API 구현
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/login/route.ts
  src/app/api/signup/route.ts
  src/lib/prisma.ts
  yarn.lock
Labels: 🪄 feature

#8 [feat] 헤더, 바텀바 구현
  package-lock.json
  src/app/(navbar)/chat/layout.tsx
  src/app/(navbar)/chat/page.tsx
  src/app/(navbar)/home/layout.tsx
  src/app/(navbar)/home/page.tsx
  src/app/(navbar)/layout.tsx
  src/app/(navbar)/like/layout.tsx
  src/app/(navbar)/like/page.tsx
  src/app/(navbar)/profile/layout.tsx
  src/app/(navbar)/profile/page.tsx
  src/app/(navbar)/recommend/layout.tsx
  src/app/(navbar)/recommend/page.tsx
  src/assets/icons/bottom_nav/fiiled_nav_folder_icon.svg
  src/assets/icons/bottom_nav/filled_nav_chat_icon.svg
  src/assets/icons/bottom_nav/filled_nav_heart_icon.svg
  src/assets/icons/bottom_nav/filled_nav_home_icon.svg
  src/assets/icons/bottom_nav/filled_nav_profile_icon.svg
  src/assets/icons/bottom_nav/nav_chat_icon.svg
  src/assets/icons/bottom_nav/nav_folder_icon.svg
  src/assets/icons/bottom_nav/nav_heart_icon.svg
  src/assets/icons/bottom_nav/nav_home_icon.svg
  src/assets/icons/bottom_nav/nav_profile_icon.svg
  src/assets/icons/left_arrow_icon.svg
  src/components/common/Header.tsx
  src/components/navbar/BottomNav.tsx
  src/components/navbar/BottomNavTab.tsx
Labels: 🪄 feature

#14 [feat] 범용 Tag 컴포넌트 구현
  src/components/common/tag/Tag.stories.tsx
  src/components/common/tag/Tag.tsx
  src/components/common/tag/type/InteractiveTag.tsx
  src/components/common/tag/type/StaticTag.tsx
  src/components/common/tag/type/styles.ts
  src/components/common/tag/type/types.ts
Labels: 🪄 feature, 🎀 FE

#17 [feat] 질문카드, 안내카드 구현
  src/assets/assets.tsx
  src/assets/character/attention_starboy.svg
  src/assets/character/attention_stargirl.svg
  src/assets/character/info_starboy.svg
  src/assets/character/thumbs_up_stargirl.svg
  src/components/InfoCard.tsx
  src/components/navbar/BottomNav.tsx
  src/components/question/AnswerButton.tsx
  src/components/question/AnswerButtonGroup.tsx
  src/components/question/QuestionCard.tsx
  tailwind.config.js
Labels: 🪄 feature, 🎀 FE

#16 [feat] 포트폴리오, 지난 달 소비 차트 구현
  package-lock.json
  package.json
  src/app/(navbar)/home/page.tsx
  src/app/layout.tsx
  src/components/chart/DoughnutChart.tsx
  src/components/chart/HorizontalBarChart.tsx
  src/components/chart/PortfolioCard.tsx
Labels: 🪄 feature, 🎀 FE

#30 [feat] 더미데이터 생성 및 스키마 업데이트
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/signup/route.ts
  src/lib/actions/calculateCurrentType.ts
  src/lib/actions/dummyConsume.ts
  src/lib/actions/dummyLoan.ts
  src/lib/actions/dummyPair.ts
  src/lib/actions/dummyProduct.ts
  src/lib/actions/dummyUser.ts
  src/lib/actions/dummyUserProduct.ts
  src/lib/constants/enums.ts
Labels: 🪄 feature, 🔐 BE

#42 [feat]홈페이지, 카드 상세페이지 구현
  src/app/(navbar)/card/[id]/layout.tsx
  src/app/(navbar)/card/[id]/page.tsx
  src/app/(navbar)/home/layout.tsx
  src/app/(navbar)/home/page.tsx
  src/components/advertisement/HanaAdCard.tsx
  src/components/chart/MonthlySpendingChart.tsx
  src/components/common/button/ReactionButton.tsx
  src/components/profile/ParingBook.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ProfileCardDetail.tsx
  src/components/profile/types/profileCardTypes.ts
Labels: 🪄 feature, 🎀 FE

#45 [feat] 페어링북 페이지 UI 구현
  src/app/(onboarding)/pairing-book/page.tsx
Labels: 🎨 design, 🎀 FE

#54 [feat] 매칭 알고리즘
  src/lib/actions/calculateCurrentType.ts
  src/lib/actions/dummyConsume.ts
  src/lib/actions/dummyLoan.ts
  src/lib/actions/dummyPair.ts
  src/lib/actions/dummyProduct.ts
  src/lib/actions/dummyUser.ts
  src/lib/actions/dummyUserProduct.ts
  src/lib/actions/getMatchPartner.ts
  src/lib/actions/makeDummyData.ts
Labels: 🪄 feature, 🔐 BE

#86 [#85] docs: Swagger Tags 순서 정렬
  src/lib/swagger.ts
Labels: 📄 docs, 🔐 BE

#96 [fix] 채팅방 정보 조회 API 수정
  src/app/api/chats/[chatRoomId]/assets/route.ts
  src/app/api/chats/[chatRoomId]/route.ts
Labels: 🔧 fix, 🔐 BE

#136 [feat]마이페이지 API연동
  src/app/(navbar)/profile/layout.tsx
  src/app/(navbar)/profile/page.tsx
  src/hooks/useLogout.ts
  src/hooks/useUserProfileQuery.ts
  src/hooks/useWithdraw.ts
  src/services/logout.ts
  src/services/withdraw.ts
Labels: 🪄 feature, 🎀 FE

#139 [fix] isDeleted User 로그인 막기
  src/app/api/login/route.ts
Labels: 🔧 fix, 🔐 BE

#144 [fix] 로그인 이후 온보딩 단계별 라우팅 세분화
  src/app/(onboarding)/pairing-book/page.tsx
  src/app/api/profiles/is-registered/route.ts
  src/components/login/LoginForm.tsx
  src/services/myProfile.ts
Labels: 🔧 fix, 🔐 BE, 🎀 FE

#153 [feat] FTTI 설문 결과 페이지 연동
  src/app/(onboarding)/question/page.tsx
  src/app/(onboarding)/result/page.tsx
  src/hooks/usePartnerFttiMutation.ts
  src/lib/store/fttiStore.ts
  src/services/partnerFtti.ts
Labels: 🪄 feature, 🎀 FE

#156 [fix] 채팅 디자인 수정 및 자산 공유 수락, 거절 UX 수정
  src/app/chatroom/[roomId]/page.tsx
  src/app/types/client-chat.ts
  src/components/chat/AssetShareButton.tsx
  src/components/chat/ChatAssetShareModal.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatProfileImage.tsx
  src/components/chat/portfolio/ChatPortfolioBottomSheet.tsx
  src/components/chat/portfolio/ChatPortfolioButton.tsx
  src/hooks/chat/useAssetShare.ts
  src/utils/dateformatter.ts
Labels: 🎨 design, 🔧 fix

#167 [refactor] 더미데이터 중복 생성 제거, 회원가입 유저 데이터 생성 transaction 처리
  prisma/seed.ts
  prisma/seeds/generatePairingAnswer.ts
  prisma/seeds/generateUsers.ts
  prisma/seeds/makeDummyData.ts
  prisma/seeds/updateUsersCurrentType.ts
  src/app/api/signup/route.ts
  src/lib/actions/generateUserConsume.ts
  src/lib/actions/generateUserFinancialProducts.ts
  src/lib/actions/generateUserLoan.ts
  src/lib/prisma/masterClient.ts
  src/lib/prisma/replicaClient.ts
Labels: 🔧 fix, 📍 refactor, 🔐 BE

#169 [refactor] 자산 공개 여부 실시간 반영
  chat-server.ts
  package-lock.json
  package.json
  scripts/loadtest.k6.js
  src/app/api/chats/[chatRoomId]/assets/accept/route.ts
  src/app/api/chats/[chatRoomId]/assets/reject/route.ts
Labels: 📍 refactor, 🔐 BE

#172 [fix] 더미데이터 생성시 트랜잭션 끊기는 오류 수정
  prisma/migrations/20250626001505_0626/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/seed.ts
  src/lib/actions/generateUserConsume.ts
  src/lib/actions/generateUserFinancialProducts.ts
  src/lib/actions/generateUserLoan.ts
Labels: 🪄 feature, 🔧 fix, 🔐 BE

#157 [feat] Quiz 퍼블리싱 및 API 연동
  src/app/(navbar)/quiz/layout.tsx
  src/app/(navbar)/quiz/page.tsx
  src/app/api/quiz-log/route.ts
  src/app/api/subject/quiz/route.ts
  src/app/api/subject/route.ts
  src/app/quiz-detail/layout.tsx
  src/app/quiz-detail/page.tsx
  src/app/types/quiz.d.ts
  src/assets/assets.tsx
  src/assets/icons/select_O.svg
  src/assets/icons/select_X.svg
  src/components/common/button/DialogButton.tsx
  src/components/common/navbar/BottomNav.tsx
  src/components/quiz/ClientProductLinkButton.tsx
  src/components/quiz/QuizAnswerModal.tsx
  src/components/quiz/QuizButton.tsx
  src/hooks/useQuiz.ts
  src/services/quiz.ts
Labels: 🎨 design, 🪄 feature, 🔐 BE, 🎀 FE

#200 [fix] Image Cropper 이미지 자르기 오류 해결
  src/components/profile/imageUploader/ImageCropper.tsx
  src/components/profile/imageUploader/ImageUploader.tsx
  src/utils/cropImage.ts
Labels: 🔧 fix, 🎀 FE

#202 Fe/fix/#196
  src/app/(navbar)/home/page.tsx
  src/app/(navbar)/profile/page.tsx
  src/assets/icons/profile_card/XMark.svg
  src/components/card/CardDetail.tsx
  src/components/common/button/ReactionButton.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ProfileCardDetail.tsx
  src/components/profile/types/profileCardTypes.ts
  src/lib/customUserData.ts
Labels: 📍 refactor, 🎀 FE

#207 [ci] 배포 스크립트 번경
  .github/workflows/deploy.yml
Labels: 🔧 fix, 🌐 ci

#208 [ci] 배포 스크립트 오류 수정
  .github/workflows/deploy.yml
Labels: 🌐 ci
